[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd worker && npm ci']

[phases.build] 
cmds = ['cd worker && npm run build']

[start]
cmd = 'cd worker && npm run deploy && npm start'